[package]
name = "Restful_Example"
version = "0.1.0"
authors = ["ggogun@gmail.com"]
edition = "2018"

[dependencies]
tide = "0.1.0"
http = "0.1"
serde = "1.0.80"
serde_derive = "1.0.80"
dotenv = "0.13.0"
dotenv_codegen = "0.11.0"
